---
title: "bib"
author: "Malory Owen & Christopher Lortie"
date: "3/5/2020"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
bibliography: bib.bib
always_allow_html: yes
---

1. Introduction

Desert ecosystems are generally stressful. Numerous factors including ultraviolet radiation, heat, water scarcity, wind, and other abiotic and biotic ecological factors contribute to this harshness relevant to plants and to animals [@Maestre2005; @Bonanomi2011]. Positive interactions between plants and animals are thus relatively common in high-stress systems [@Lortie2006]. Facilitation is broadly defined as the association of a benefactor plant species with protegee plants or animals by increasing germination, growth, and recruitment of protegee species [@Franco1989]. In arid ecosystems, facilitation by foundation species can provide resources like water, shade, and pollinators [@FloresTorres2017; @MirandaJacome2013; @Mitchell2009], or protection from trauma by herbivory, trampling, freezing temperatures, predation, and wind [@GomezAparicio2008; @Parker1989; @Tewksbury2001; @Nobel1980]. Benefactor species which facilitate many interspecifics in an ecosystem are known as foundational species [@Angelini2011; @Almeida2018] and tend to dominate an ecosystem. Shrub species have been documented as the most common foundational species globally, though trees and cacti are two other common vegetative benefactors [@Filazzola2014]. These large, sturdy plants are largely responsible for habitat infrastructure of wildlife throughout an ecosystem [@Callaway1997; @GelmiCandusso2017]. While most studies have focused on plant-plant facilitation [@Callaway2007], there is also evidence for the importance of plant-animal interactions in stressful environments [@Lortie2016; @Bertness1999; @Arsenault2002]. However, a more comprehensive understanding of what resources or services animals contribute to the interaction may illuminate pathways of habitat creation that, so far, is less understood.

Compared to facilitation which can often be a +/0 interaction, mutualism is a +/+ interaction. Mutualism is a category of positive interaction wherein the participating parties both benefit from an interaction, usually in the form of resource acquisition that increases the survival or fitness of the parties [@Barker2017; @Bronstein2009; @Bronstein2001]. Pollination and seed dispersal are two common forms of mutualism that directly create and maintain habitat in most ecosystems, both of which are performed by birds found in desert ecosystems. Birds are unique in their mutualistic interactions with plants in that they can travel far distances with seeds in their guts [@Spiegel2007], deposit large pollen loads [@Ramsey1988], scarify seeds in their gut, thereby promoting germination rates [@Traveset2002], and participate in general and specialized interactions which produce habitat infrastructure [@Devictor2008]. Despite this, birds are understudied as important actors in arid ecosystems compared to insects like bees and beetles. Examining the relationship from the bird and the cactus perspective in concert will lead to a better understanding of how ecosystems maintain their own habitat, and how managers can employ these natural systems for conservation purposes. 

This concert of interacting species is, however, dependent on temporal and geographic limitations. Phenology in desert ecosystems can vary widely due to the extreme plasticity of temperature and precipitation [@Henen1998] including cacti & shrubs [@Schwartz2003; @Beatley1974; @Jordan1982; @Nobel1981] and bird migration and breeding seasons [@Sillett2002; @Runge2017; @Fahse1998]. This suggests that for animals that rely on or associate with cacti for resources, timing is critical [@Buler2007]. Phenological mismatch has been studied in deserts [@Kellermann2015] and is important to explore interactions through time and space at different reproductive stages of the foundation plant species or pollinating/seed dispersing birds in a system, as these limitations determine the capability of plant/bird reproduction to occur, and therefore, habitat creation. However, we must first determine the potentiality for these interactions to even occur before we can determine the implications of phenological mismatches.

In this study, we examined the hypothesis that there are associations between birds and foundation plant species such as shrubs and cacti, and these relationships change with phenology. Our research questions are: 1) How does desert bird community change between migratory/flowering seasons (hereafter referred to as spring) and breeding/fruiting seasons (hereafter referred to as summer)? 2) How do birds associate with available plant mesohabitats or exhibit different behaviors in different seasons? And 3) are mesohabitats fostering certain behaviors among birds? We predict that 1) bird community structure will be different in the spring season than in the summer season, 2) observed mesohabitats and behaviors will be defined by the birds’ functional and taxonomic diversity, and 3) bird behavior changes as their occupied mesohabitat changes. 


2. Methods

2.1 Study Site

The Mojave Desert is located on the South Eastern border of California, with most of the land being designated as the Mojave National Preserve under the United States National Park System. Directly adjacent to the public lands of the preserve is the Sweeney Granite Mountains Desert Research Center (34°48′20″N 115°39′50″W), which is land owned by the University of California as a part of the UC Reserve System. This land is only available to researchers and classes, thereby preventing interference from public visitors. Located in the Granite Mountains of the Eastern Mojave Desert, the 3,600 hectares of the research center’s elevation ranges from 1,128 to 2,071 m. Like many other arid ecosystems, rainfall varies significantly throughout the year, though the yearly average being 22 cm per year. The July average minimum and maximum is 20°C and 33°C respectively, while the December average minimum and maximum is -1°C and 8°C. Geologically, the site is unique with alluvial fans and bajadas to granitic pinnacles. Springs, seeps, and washes are common topographical features throughout the land.

2.2 Study system

This study site within the reserve system is dominated by perennial woody and succulent shrubs such as Cylindropuntia acanthocarpa, Yucca mohavensis, Larrea tridentata, Ambrosia salsola, Pinus monophylla, and numerous other shrub species. A hub of desert diversity, 156 birds, 42 mammals, 2 amphibians, and 504 species of vascular plants have been documented throughout the reserve. The field work for this study was conducted from May to August of 2019, a spring and summer following an unusually strong rainy season. Higher winter rain levels typically result in stronger blooms in this area, with this year being no exception (***rainfall levels in 2019 winter). However, an unusually cool early spring led to a delay for many thermally induced blooms such as several Cylindropuntia ssp. 

The avian community of the Mojave Desert includes typical species of the American Southwest, but also is home to desert obligate species which rely on plant species only found in wild desert areas (e.g. the Cactus Wren, Campylorhynchus brunneicapillus). There are currently over 159 bird species on the Sweeney Granite Mountains Desert Research Center [@Gurin2012], and a complete list of all known avian species to the field site is available via the site’s website. 

2.3 Field observations

To sample the bird community makeup, we repeated walked a 500-meter line transects over a two-hour period at cooler day times, which was associated with peak bird activity from 7-10am or 5-8pm (N=41). We sampled two individual line transects, which were spaced 80 meters a part due to physical blocks of craggy mountains. The starting coordinates for transect 1 and 2 were 34.78299, -115.662 and 34.78303, -115.663, respectively. A single observer familiar with the local bird species recorded all visual (n=755) or audial (n=463) bird queues and identified each observation to species (though some female/juvenile hummingbirds were identified only to family due to the visual similarity between species). However, we only included visual observations of birds in mesohabitat and behavioral analyses, since the data is less fine. Flyovers (defined as birds flying roughly 25 feet above the shrub line that did not land within sight) were not included as an observation. In addition to species, we also recorded behavior (as designated by an ethogram), mesohabitat, geographic coordinates, the time of the sighting/hearing, and an estimate of the distance from the transect (<25 meters, 25-50 meters, or >50 meters). We also took photographs of birds using a Nikon D5300 camera equipped with a Sigma 150-600mm lens which served as identification aids and behavioral/mesohabitat records. 

Behavior and mesohabitat functioned as dependent variables for each observation of a bird. Behavioral observations were then categorized into broader behaviors (active movement, cleaning, feeding, inactive, and territorial/mating). Mesohabitat level observations were distilled into 2-level (vegetative or non-vegetative) and 3-level (cactus, shrub, or other). Trophic guild and migratory class were the metrics we used to define functional diversity. We categorized all observed species into trophic guilds using Foraging Guilds of North America [@Graaf1985] and into migratory classes using *Common Birds of the Sweeney Granite Mountains Desert Research Center* [@Gurin2012]. Taxonomic diversity was originally recorded to species level, and then grouped into broader taxonomic designations (family and order). 

2.4 Statistical Analyses

Using each line transect walk as a level of replication, we calculated species abundance (A), richness (S), Turnover (T), and evenness (J) using the R Vegan Package [@Oksanen2019]. Additionally, we calculated Simpson’s Diversity Index (D) and Shannon’s Diversity Index (H) to encourage transparency on the influence of evenness or richness, respectively. Using these different metrics for community structure, we created linear regression models to determine differences in community structure in spring and summer, excluding species richness, for which we performed a general loglinear model (due to the non-normal, poisson distribution of species richness through both seasons). We included each walk of a transect in the models as a random effect.
Additionally, to determine the species variance impact on community structure, we performed a Principle Components Analysis for both spring and summer.  We then composed two distance-based Moran's eigenvector maps for each season as a visualization for the species’ variance. 

To determine the impact of bird taxonomic on the likelihood of mesohabitat use, we compared bird species abundance across different levels of mesohabitat. On that same note, we determined the impact of bird functional diversity on mesohabitat use, we compared bird trophic guild abundance as well as bird migratory class abundance across different levels of mesohabitat. Because we observed birds associating with 11 different types of mesohabitat, we compressed these data into 3-level responses (shrub, cactus, or other) and 2-level responses (vegetation or non-vegetation). We conducted a One-way ANOVA across these three or two mesohabitat levels to determine if there was a difference in mesohabitat type birds most often associated with. We conducted this analysis both within and between seasons. 

Similarly to our mesohabitat association tests, we compared bird taxonomic diversity (represented as bird species abundance) across different behavior types both, as well as bird functional diversity (represented as trophic guild abundance and migratory class abundance). Again, because we observed 15 different ethogram-defined behaviors, we binned behaviors into 5 broad behaviors: active movement, inactivity,  cleaning, feeding/foraging, and territorial/mating. We conducted a One-way ANOVA across these 5 behavior levels to determine if behavior types exhibited by birds significantly differed. Again, we conducted this analysis both within and between seasons. When an ANOVA model showed significant differences in these response variables, we used a Tukey Honest Significance posthoc test to determine exactly which behaviors were more  or less frequently exhibited.

To examine the influence of a bird’s mesohabitat on its behavior, we performed a two Pearson’s Chi-squared test; the first including 3-levels of mesohabitat (shrub, cactus, or other) as the independent variable, the second broadening our perspective with 2-levels of mesohabitat (vegetative or non-vegetative). Again, we compared within and between seasons. However, due to the small cell size of “cleaning” level of bird behavior leading to incorrect Chi-squared approximation, we removed “cleaning” as a level, eliminating 5 observations out of 750 total bird interactions. Any Chi-squared tests yielding significant differences were then analyzed using a Bonferroni posthoc test. All analyses were performed in R version 3.5.1 [@Team2017]. 

3. Results	

3.1 Community structure between seasons

Spring had significantly higher levels in all metrics of community structure than summer, except in species turnover (Table 1; Fig. 1). Simpson’s Diversity Index accounts more for evenness in it’s metric, whereas Shannon’s Diversity Index accounts more richness.  
Seeking an 80% of species variance explained by included principle components, our principle components analysis showed that, for spring, 80.68% of variance in bird species is explained by the first 6 principle components. Summer, however, had 89.24% of species variance explained by principle components 1 and 2 (Fig. 2). Considering that a total 43 species were observed during this study (Table 2), the compression of this community into 6 and 2 principle components shows clarity among represented species. 

3.2 Mutualistic interaction possibilities

Comparing the differences in bird species abundance (Table 2) between shrub, cactus, and other mesohabitat types, we found no significant difference both within seasons and between spring or summer. This was also true for our two-level analysis of vegetative or non-vegetative mesohabitats, suggesting no difference in which mesohabitats birds are associating with in spring or summer. There was also no statistical distinction between either of the functional diversity metrics. Trophic guild abundance and migratory classes did not differ within or between seasons, regardless of the number of mesohabitat levels defined (Table 5; Fig.3). 

Behaviors exhibited by bird species, however, did differ. When comparing bird species abundance across both seasons, territorial/mating behaviors were higher in spring than cleaning or feeding behaviors in either season and higher than inactivity in summer. For trophic guild abundance across both seasons, we again found that territorial/mating behaviors were higher in spring than cleaning behaviors in spring or summer. However, when representing functional diversity as migratory classes, we found no significant differences in behavior types exhibited (Table 5; Fig. 3). 

3.3 Mesohabitats’ influence behavior

Lastly, we compared mesohabitats influence on bird behavior. When comparing the influence of vegetative or non-vegetative mesohabitats on behavior & shrub, cactus, or other mesohabitats on behavior, we found significant differences between both the three-level mesohabitat as predictors (Pearson’s Chi-squared Test, X2=26.47, df=6, p<0.001) and the two-level mesohabitat as predictors (Pearson’s Chi-squared Test, X2=23.66, df=3, p<0.0001). The Bonferroni test showed that mesohabitats other than shrubs or cacti had a positive influence on active movement, and a negative influence on territorial/mating behaviors (Fig. 4). When we broadened our perspective, we found that vegetative mesohabitats had a negative influence on active movement but a positive influence on territorial/mating behaviors, and that non-vegetative mesohabitats had a positive influence on active movement and a negative influence on territorial/mating behaviors (Fig. 4). 

4. Discussion

Positive interactions, including mutualism, are responsible for habitat infrastructure across ecosystems where cohabitation can be beneficial for all parties involved [@Cardinale2002]. This is especially true in ecosystems where abiotic and biotic stressors are abundant, such as degraded arid systems and high-elevation alpine systems [@Graff2011; @Choler2001]. In this study, we investigated the relationship between birds and their biotic habitat to determine the capacity and for mutualistic interactions during different phenological stages (for plants) and migratory stages (for birds) that are important for desert habitat creation and maintenance. Specifically, we tested for differences in bird community structure between spring and summer, for the influence of taxonomic and functional diversity on mesohabitat and behavior, and for the influence of mesohabitats birds associate with on bird behavior. 

4.1 Does community structure change between spring and summer? 

In our bird community structure between seasons, we found support for the prediction that each season had different species makeups. In fact, we found that spring consistently had more species, more individuals, more evenly distributed individuals in all species, and higher diversity (both in terms of Shannon’s Diversity Index and Simpson’s Diversity Index). However, we did not see significant turnover throughout the season, showing that there was a consistent representation of species throughout each season. These findings support the prediction that bird community structure is changing throughout the seasons. Therefore, we suggest that the shifting of community structures through migration has influence one way or the other on the capacity for mutualistic interactions linked to phenological stages such as pollination and seed endozoochoric seed dispersal. 

Our Principle Components Analysis showed that the in spring, the abundance of bird species was less easily collapsible than the abundance of summer bird species. This makes sense considering metrics of diversity, abundance, richness, and evenness all were higher in spring. Similarity among species within seasons is higher in summer, suggesting less opportunity for diverse interactions between plants and birds in the summer. Summer months in deserts, being much hotter and dried than the spring months, are known to exhibit lower diversity of many vertebrates during this time as species migrate to cooler/wetter areas, or as they enter torpor to conserve energy during this harsh time [@Tonkin2017; @Boyles2017; @Geiser1995]. While our methods of observation could not account for those species or individuals removing themselves from the desert, our methods do account for active wildlife; any birds that are active during this time of the year and during the day are represented in our study. 

As the two communities do appear to differ between spring and summer, this community structural change suggests the opportunity (or compulsion) for plants benefitted by birds to adapt to these birds’ constraints. 

4.2 How do birds associate with mesohabitats and exhibit behaviors?

Whether or not these shifting community structures do result in a changed use of habitat for birds/a changed interaction between birds and plants required further investigation. Mesohabitat associations did not differ when we considered taxonomic variation in birds as an explanatory variable; this was true when we compared spring and summer mesohabitat associations against each other, but also when we isolated each season. That is to say, birds associated with shrubs, cacti, and other mesohabitats equally often in spring and summer. This is true even when we broaden our perspectives, as birds associate with vegetation and non-vegetation equally often in spring as they do in summer. However, we did see that behaviors exhibited by birds were not consistent across seasons. Territorial or mating behavior was higher in spring than cleaning or feeding in either season and higher than inactivity in summer. 

These findings do not entirely support our original hypothesis; we see that birds will not alter their mesohabitat associations with the seasons, but instead will alter their behaviors. Remembering that summer is a much hotter and drier seasons, this is consistent with previous work showing that many animal species must behaviorally adapt to harsh environments [@Filazzola2017]. Additionally, territoriality or mating behaviors are the most common in early spring, which aligns with knowledge on the phenology of birds, as nests and mates are determined in spring for many migratory species [@Lima2009]. However, the fact that mesohabitat did not differ reflects the importance of consistency and availability of all mesohabitats throughout the seasons in desert ecosystems. 

4.3 Are mesohabitats fostering certain behaviors?

Lastly, we saw that depending on what mesohabitat a bird was, it's behavior. This is to say that mesohabitat association had a clear influence on exhibited bird behavior. This idea is consistent with our previous conclusions that consistency and availability of mesohabitats is deeply important for birds behavioral expression. We see similar stories across many species, in that behaviors of many species are exclusive to certain environments [@Fink2006], but our findings show the importance of finer-scale mesohabitats to desert bird behavior.

5. Conclusions

Desert habitats, like many other environments, are undergoing severe habitat loss and degradation due to a multitude of anthropogenically-influenced factors such as climate change, invasion of non-native species, livestock grazing, increased human developmentm, and others [@Lovich1999; @Nielsen2015; @Pfahl2017; @Singh2013; @Smith2011; @Gutzwiller2003; @Hernandez2014; @RodriguezEstrella2007]. Our results show the importance of management for infrastructural plant species, as the presence or absence of these foundational and keystone plants have strong implications on the expression of bird behavior. We hope that this information helps environmental managers make informed decisions on how to facilitate successful taxonomic diversity, food-web interactions, and migratory safe-havens. 

