---
title: "Thesis Citations"
author: "Malory Owen"
date: "6/21/2020"
output: word_document
bibliography: thesis_bib.bib
---

Introduction
Background
	Habitat use, broadly defined, is the way an animal interacts with its surroundings, be they biotic or abiotic. The dimensions of habitat use that we study may take several forms; Macrohabitat use generally describes large-scale interactions with variety in participants, while microhabitat use refers to a homogenous scale of environment [@Price1978; @Jorgensen2004]. Despite the “macro” and “micro” prefixes, these definitions are largely based on variability of a habitat-in-question, thus the reality of a macro/microhabitat is highly dependent on the ecosystem at large. For highly mobile individuals (such as birds), an individual’s surrounding microhabitat can rapidly shift as the individual transverses space. Microhabitat use relies on reactions based on a variety of environmental inputs. The plant taxonomic heterogeneity of a habitat provides resource partitioning [@Schoener1974], so access to food, water, shelter, etc. will be differentiated between space. Optimal foraging theory is based on this idea, to some extent, in that different microhabitats provide different resources [@Pyke1984]. However, predator avoidance is another strong contributor to habitat selection based on the actor’s morphology, species, lifestage, life history, etc. [@Longland1991].  
	Desert habitats are generally stressful. Numerous factors including ultraviolet radiation, heat, water scarcity, wind, and other abiotic and biotic ecological factors contribute to this harshness relevant to plants and to animals [@Maestre2005; @Bonanomi2011]. Positive interactions between plants and animals are thus relatively common in high-stress systems [@Lortie2006]. Facilitation is broadly defined as the association of a benefactor plant species with protegee plants or animals by increasing germination, growth, and recruitment of protegee species [@Franco1989]. In arid ecosystems, facilitation by foundation species can provide resources like water, shade, and pollinators [@FloresTorres2017; @MirandaJacome2013; @Mitchell2009], or protection from trauma by herbivory, trampling, freezing temperatures, predation, and wind [@GomezAparicio2008; @Parker1989; @Tewksbury2001; @Nobel1980]. Benefactor species which facilitate many interspecifics in an ecosystem are known as foundational species [@Angelini2011; @Almeida2018] and tend to dominate an ecosystem. Shrub species have been documented as the most common foundational species globally, though trees and cacti are two other common vegetative benefactors [@Filazzola2014]. These large, sturdy plants are largely responsible for habitat infrastructure of wildlife throughout an ecosystem [@Callaway1997; @GelmiCandusso2017]. While most studies have focused on plant-plant facilitation [@Callaway2007], there is also evidence for the importance of plant-animal interactions in stressful environments [@Lortie2016; @Bertness1999; @Arsenault2002]. However, a more comprehensive understanding of what resources or services animals contribute to the interaction may illuminate pathways of habitat creation that, so far, is less understood.
	Most studies examining habitat use focus on single populations of interactors and one category of influence (i.e., a single resource or a single predator). However, these influences are difficult to untangle because they exist at a multitude of scales and are rarely independent themselves [@Webb2010; @Buler2007]. Studies also tend to examine these relationships as a unidirectional flow rather than as a network of interactions that change depending on each party and other abiotic/biotic factors @Moore2000]. This work is critical; however, holistic studies that examine interactions at the community level paint more complete tableaus of critical interactions for ecosystem functioning.
	This concert of interacting species is, however, dependent on temporal and geographic limitations. Phenology in desert ecosystems can vary widely due to the extreme plasticity of temperature and precipitation [@Henen1998] including cacti & shrubs [@Schwartz2003; @Beatley1974; @Jordan1982; @Nobel1981] and bird migration and breeding seasons [@Sillett2002; @Runge2017; @Fahse1998). This suggests that for animals that rely on or associate with cacti for resources, timing is critical [@Buler2007]. Phenological mismatch has been studied in deserts [@Kellermann2015] and is important to explore interactions through time and space at different reproductive stages of the foundation plant species or pollinating/seed dispersing birds in a system, as these limitations determine the capability of plant/bird reproduction to occur, and therefore, habitat creation. However, we must first determine the potentiality for these interactions to even occur before we can determine the implications of phenological mismatches.
	Phenology, however, does not solely determine the plant reproductive output and, consequently, resource value to interacting animals (like birds). Each plant species has different floral and fruiting output with varying numbers of reproductive structures that interacting animals may benefit from. This variety is linked to plant coevolution with interacting pollinators and seed dispersers [@Jordano1987]. Even so, these reproductive output features are strongly influenced by other morphological characteristics of a plant due to a finite amount of nutrients, resources, and energy, thereby requiring tradeoffs between reproductive structures and non-reproductive structures [@Bazzaz1997]. This allocation of resources in a plant determines factors such as plant size, chemical defenses, and reproductive output [@Obeso2004] often in an inverse relationship [@Hasegawa2001].
	Two of these factors, physical size and reproductive output, influence plant-animal interactions that then influence a plant’s reproductive success and an animal’s resource availability. Physical size as a combination of plant height and canopy width is directly linked with pollination frequency for the plant individual itself as taller, larger plants stand out against their shorter neighbors, thereby attracting flying pollinators such as birds and insects [@Wolf1991; @Mitchell1994]. However, number of inflorescences also positively influences a plant’s number of pollination visitations (to diminishing returns), as showy floral displays similarly attract flying pollinators [@Ohashi2001]. These two features of a plant will then influence the relationship between pollinators and plants.  
	However, the allocational tradeoffs between physical size and reproductive output, being two structural depositions of plant resources, are thus at odds as the plant’s morphological makeup. Despite the strong implications for agriculture and conservation fields of biology, these tradeoffs are not well documented. As a precursor to the primary portion of this study, we conducted a systematic review to examine the extent to which allocational tradeoffs between plant physical and reproductive structures were measured. 
	In this study, we examined the hypothesis that there are associations between birds and foundation plant species such as shrubs and cacti which change with shifting phenology. In reference to “associations” we include presence/absence data as well as behavioral data. By including both metrics, we hope to more accurately reflect these interactions; associations alter functionality based on the birds’ behaviors. Our research question is: How do desert bird communities and associations with foundation plant microhabitats change between migratory/flowering seasons (hereafter referred to as spring) and breeding/fruiting seasons (hereafter referred to as summer)? We predict that 1) abundance and diversity of birds is greater near foundation plant species, 2) observed microhabitats will be defined by the birds’ functional and taxonomic diversity, and 3) seasonality changes the associations between foundation plants and the bird community.

Methods 
Study Site
	The research was done at the Sweeney Granite Mountains Desert Research Center (34°48′20″N 115°39′50″W) in the Mojave Desert. The 3,600 hectares elevation ranges from 1,128 to 2,071 m and is not accessible to visitors and thus any disturbance. Rainfall varies significantly throughout the year with a mean annual precipitation ranging from 34 t 310 mm per year [@Urban2009], and no typically no precipitation in the summer months. The long-term July daily average minimum and maximum is 1°C and 40°C respectively [(1937-2007 records; @WRCC2008]. The site is dominated by perennial woody and succulent shrubs such as Cylindropuntia acanthocarpa, Yucca mohavensis, Larrea tridentata, Ambrosia salsola, Pinus monophylla, and numerous other shrub species [@Andre2006]. There have been 156 birds, 42 mammals, 35 reptiles, 2 amphibians, and 504 species of vascular plants documented at the reserve [@Gurin2012; @Mammals; @Stewart2008; @Andre2006). 
Study species
	While the Mojave boasts an array of diverse plants, a handful of foundational plant species dominate the landscape. *Cylindropuntia acanthocarpa*, or Buckhorn Cholla, is a shrub-like cactus with an irregular branching pattern. *Larrea tridentata*, or Creosote Bush, is a large, long-lived deciduous shrub that is well documented as a benefactor species for plants and animals. *Yucca schideigera*, or Mojave Yucca, is a flowering plant native to the region with several specialist and generalist relationships with fauna of the region. While there are many other plant species found in the study site, these three are the most abundant of plant species and accounted for most interactions documented in this study.  
	The avian community of the Mojave Desert includes typical species of the American Southwest but is also home to desert obligate species which rely on plant species only found in wild desert areas (e.g. the Cactus Wren, *Campylorhynchus brunneicapillus*). There are currently over 159 bird species on the Sweeney Granite Mountains Desert Research Center [@Gurin2012], and a complete list of all known avian species to the field site is available via the site’s website. The most common bird documented over both seasons was *Amphispiza bilineata*, or the Black-throated Sparrow. An insectivore, herbivore, and granivore, this year long resident of Southwestern deserts [@Graaf1985] was seen or heard at every sampling replication. 
Experimental Design
	We used a 500-meter line transect over two-hour period block to sample the bird community. Transects were deployed between 7-10am or 5-8pm depending on daily temperatures, which were associated with peak bird activity. Two individual line transects were used and spaced 80 meters apart. The starting coordinates for transect 1 and 2 were (34.78299, -115.662) and (34.78303, -115.663) respectively. A single observer familiar with the local bird species recorded all visual or auditory bird cues and identified each observation to species. Some female/juvenile hummingbirds were identified only to family due to the visual similarity between species. In each instance, microhabitat was also recorded as list the categories here.. However, we only included visual observations of birds in microhabitat and behavioral analyses. Flyovers (defined as birds flying roughly 25 feet above the highest vegetation at site that did not land within sight) were not included as an observation. In addition to species, we also recorded behavior as designated by an ethogram (Appendix C), microhabitat, geographic coordinates, the time of the sighting/hearing, and an estimate of the distance from the transect(<25 meters, 25-50 meters, or >50 meters). We also took photographs of birds using a Nikon D5300 camera equipped with a Sigma 150-600mm lens which served as identification aids and behavioral/microhabitat records (Supplemental Material A).
Statistical Analyses
	Behavior and microhabitat functioned as dependent variables for each observation of a bird. Behavioral observations were then categorized into broader behaviors (active movement, cleaning, feeding, inactive, and territorial/mating). Microhabitat level observations were distilled into two levels (vegetative or non-vegetative) and three levels (cactus, shrub, or other). Trophic guild and migratory class were the metrics we used to define functional diversity. We categorized all observed species into trophic guilds using “Foraging Guilds of North America” [@Graaf1985] and into migratory classes using Common Birds of the Sweeney Granite Mountains Desert Research Center [@Gurin2012]. Taxonomic diversity was recorded to species level and thus represented in the statistical analyses.
	Using each line transect walk survey as a level of replication, we calculated species abundance (A), richness (S), turnover (T), and evenness (J) using the R Vegan Package [@Oksanen2019]. Additionally, we calculated Simpson’s Diversity Index (D) and Shannon’s Diversity Index (H) to encourage transparency on the influence of evenness or richness respectively [@Morris2014]. Using these different metrics for community structure, we used linear regression models to determine differences in community structure in spring and summer, excluding species richness (for which we used a general linear model due to a non-normal, Poisson distribution) [@Mayorga2020]. To assess the species variance impact on community structure, we conducted a principal components analysis of both spring and summer. We then composed two distance-based Moran’s eigenvector maps for each season as a visualization for the variance by species.
	To test our main hypothesis examining associations between birds and foundation plant microhabitats, we conducted general loglinear models [@Donald2001]. When considering species as the diversity index, the first model examined species count data present at each microhabitat, the second examined species richness at each microhabitat, and the third examined the behavior counts at each microhabitat. We also conducted two additional GLMs to assess the birds’ functional diversity metrics as indicators for mesohabitat use; functional diversity was first modelled first with trophic guilds and then with migratory classes (Table *** with models written out). However, it should be noted that to prevent overdispersion of our trophic guild model, we could not include trophic guild as a term in our model, though the counts of each trophic guild were still grouped by trophic guild. Microhabitats were simplified into one of three categories: open, cactus, or shrub, as these microhabitats provide different amenities to birds and vice versa. In these models, we included each survey as well as the mean average air temperature at the start of each survey session recorded by the research center’s weather station, as air temperature plays a role in animal behavior in desert ecosystems (Appendix A) [@Ivey2020]. Additionally, we conducted a general linear model contrasting seasons, microhabitats, and behaviors of only the most commonly spotted species, the Black-throated Sparrow, to assess if this dominant bird species replicates the findings of our community-wide statistics. 
	All figures were plotted using the ggplot2 R package [@Wickham2016]. All analyses were performed in R version 3.5.1 [@Oksanen2019], and all R Markdown code can be found on GitHub at https://github.com/maloryowen/Desert-Bird-Habitat-Use. Photo documentation of birds can be found at https://www.flickr.com/photos/189022785N06/albums/72157714811897947. 

Results
	Throughout the entirety of the study, we visually observed 755 birds and heard 467 birds. However, because only birds that were seen could be classified by behavior and microhabitat, those 467 heard-only birds were not included in the data analysis, though the complete visual and auditory dataset can be found at https://github.com/maloryowen/Desert-Bird-Habitat-Use. During the spring, 539 birds were seen while only 216 birds were seen in summer. 
Overall community structure between seasons
	Using Shapiro Normality Tests, we found that all metrics for community structure were normally distributed except species richness. All measures of avian community structure, except species turnover, were significantly greater in during the spring census (Linear Model/General Linear Model, Table ***; Fig. 1). Spring and summer mean ± standard error was 20.40 ± 1.78 & 10.15 ± 1.28 for species abundance, 1.86 ± 0.07 & 0.73 ± 0.12 for Shannon-Weaver Index, 8.56 ± 0.54 & 3.20 ± 0.41 for species richness, 0.80 ±0.02 & 0.38 ± 0.06 for Simpson’s Diversity Index, 0.88 ± 0.02 & 0.57 ± 0.07 for species evenness, and 0.67 ± 0.03 & 0.66 ± 0.05 for species turnover. 
	Our Principle Components Analysis allows us to determine which species in each season vary together, thereby showing how variable the community species were in each season. For both seasons, we decided that the important principle components would be comprised of those at which 80% of variance was explained by the addition of a principle component. During the spring, this was delineated by the first six principle components, whereas in summer, the first two principle components reached 80% explanation of variance (Appendix E *** use barplots of relative eignevalues). To determine which species in a principle component were varying together, we chose the eigenvalue of 0.50 as a cut-off point for inclusion, as this value presented itself as a natural break in the principle component dataset. For spring species (Figure *** A), the first principle component (which accounted for 46% of variance) was composed of 3 species which varied together: the Black-tailed Gnatcatcher, the Black-throated Sparrow, and the Blue-gray Gnatcatcher. The second principle component accounted for 58% of variance and only the Blue-gray Gnatcatcher and White-throated Swift varied together. The third principle component consisted of 67% of the variance and only the White-throated Swift accounted for the variance; this is similar to the fourth principle component which accounted for 75% of the variance and represented only the Verdin as a variance. And finally, the sixth principle component for spring accounted for 81% of the variance of the dataset, with the White-throated Swift and Black-tailed Gnatcatcher varying together. For the summer species (Figure *** B use the eigenvalue map), the first principle component accounted for 66% of the community’s variance, with Gambel’s Quail supporting most of this variance alone. The second principle component, however, accounted for 89% of the community’s variance with Gambel’s Quail and the Black-throated Sparrow importantly varying together. 
Microhabitat & Behavior in Seasons
	Our model to compare species abundances between seasonal microhabitats only, we found that the only significant differences between seasonal microhabitats were found between open habitats in the spring and open habitats in the summer, with open summer microhabitats displaying higher species counts (Appendix E; General Linear Model, p-value = 0.0327). However, our model to compare species richness between seasonal microhabitats showed more  complex results. Spring cactus microhabitats were less species rich than spring open and spring microhabitats (General Linear Model, p-value = 0.0233; p-value = 0.0144). However, open spring habitats were more species rich than summer cacti, summer open, & summer shrub habitats (General Linear Model, p-value = 0.0001, p-value < 0.0001, p-value = 0.0009). Lastly, spring shrub microhabitats were richer than summer cacti, summer open, and summer shrub microhabitats (General Linear Model, p-value < 0.0001, p-value < 0.0001, p-value = 0.0005). 
	How, though, were bird behaviors represented at each seasonal microhabitat? We found that of all combinations of only microhabitats and behaviors, territorial/mating behaviors at shrub microhabitats were more common than inactivity or feeding behaviors at cacti (General Linear Model, p-value = 0.0026, p-value = 0.0231). However, including season as a term in our model revealed more information. A total of eleven combinations of behaviors at seasonal microhabitats were significantly different (Table *** ; Figure ***). 
	These models used taxonomic diversity (as delineated by species), however, bird functional diversity also provided insight to the interactions between these foundation plant microhabitats and birds. Bird trophic guild abundance was significantly greater at spring shrubs than at spring cacti or spring open microhabitats (Appendix E; General Linear Model, p-value = 0.0318, p=value = 0.0384). However, when considering migratory class abundance, there were no significant differences between seasonal microhabitats (Appendix E). Black-throated Sparrows were visually observed 129 times throughout both seasons. When removing community diversity in the model by removing species as a grouping factor and comparing habitat use in only Black-throated Sparrows, we did not find any statistical difference among abundances of any behaviors in either season and microhabitats (General Linear Model, Appendix E, Table ***). 
Discussion
	Positive interactions are responsible for habitat infrastructure across ecosystems where cohabitation can be beneficial for all parties involved [@Cardinale2002]. This is particularly pressing in ecosystems where abiotic and biotic stressors are abundant, such as degraded arid systems and high-elevation alpine systems [@Graff2011; @Choler2001]. In this study, tested the hypothesis that there are associations between birds and foundation plant species such as shrubs and cacti which change with shifting phenology. Our results do indeed support our hypothesis to some degree, though the interaction links are complex. The presented evidence suggests that mutualistic interactions with foundation plants is ecologically important in this system, with bird habitat use (as presented by presence and behavior at microhabitats) being influenced by foundation plants. 
	Our first prediction that “bird community structures in this desert system differ between spring and summer” was supported by our results. We were able to see that values for diversity metrics were higher in spring, a time of migration for birds and floral production in foundation plants [@Rathcke1985]. Additionally, our PCA revealed that species abundance was more variable during spring suggesting that the community composition is more diverse during this time. Typical changes in biodiversity due to the arrival and departure of migratory species have been shown to influence resident species’ success in reproduction and resource acquisition, though evidence is conflicting and anthropogenic changes may impact this [@Cox1968; @Greenberg1993; @RamirezCruz2020]. When considering plants in seasonal areas (where migration is most likely to occur) [@Salewski2007], spring is a period in which floral offerings to migratory birds benefit both species, with pollination being an act of mutualism [@Linhart1980]. This increased diversity during a migration season was expected, as summer conditions in deserts often result in lower frequencies of vertebrate activity due to intense conditions [@Tonkin2017; @Boyles2017; @Geiser1995]. This provided for a clear path forward to analyze how habitat use changed among these differing communities.
	Our second and third predictions, being “abundance and diversity of birds is greater near foundation plant species” and “seasonality changes the associations between foundation plants and the bird community”, while supported, require more nuanced interpretation to understand fully. Foundation species are not important factors for bird species counts, as only open sites experience any difference between seasons. In summer, we see increased fruit production for frugivorous birds in many ecosystems [@McGrath2009] (anecdotally, we often saw orioles and other frugivores at the Mojave Yucca eating their ripe fruit), a benefit to birds and plants. We also see harsher ultraviolet radiation, water scarcity, and intense heat in desert summers. In regard to counts, we may not have observed more birds associating with foundation species in summer; but birds were not exposing themselves to open habitat as often in summer—where these conditions are harsher [@Lortie2016]. It is interesting to consider that many birds may be reducing their habitat use of open spaces in summer but are not necessarily finding refuge in foundation plants. It should be noted that this study site is nestled within large granitic rock formations that support a slightly different plant community, but these locations were outside our sampling space. This is important as we know benefactor rocks, or nurse rocks, have been shown to be facilitators for plants and provide habitat for desert birds [@Peters2008; @Warning2015]. 
	However, these results suggesting that foundation plants are not important for birds during harsher seasons only applies to species abundances, not species richness. In fact, species richness may in fact be a better indicator of biodiversity, and therefore health, of an ecosystem [@Tilman2014]. In either season, shrubs are the most species rich microhabitat, though spring is richer than summer. Cacti support the least species richness compared to other microhabitats in any season, and do not differ within seasons. This was surprising, considering that we including Mojave Yucca as a cactus microhabitat, which produced large, fleshy, edible fruits in summer (though it is not actually a cactus, we argue that it is functionally similar in terms of fleshy perches and sharp points providing protection from larger predators, a major threat to bird nest survival) [@Ricklefs1969]. Our previous results suggesting that open environments are less attractive to birds in summer held true, continuing to support the idea that open areas are less inhabited in desert summers, likely due to higher ultraviolet radiation, water scarcity, and heat. Our findings also support previous work detailing the importance of foundation shrub species for desert animals and their behaviors [@Aukema2002; @Bauwens1996]. However, the shrub-specific findings do illuminate caveats to a simple definition stress-gradient hypothesis as shrub species were richer during less stressful environmental season, though some studies have already discussed the importance of scale in regards to the stress-gradient hypothesis [@Lortie2006; @Maestre2005). Instead, we suggest that it is the stress the mobile species (in this study, birds) undergo which determines associations between interactors. 
	It was, however, the use of these habitats, behaviorally, that provided significant, albeit complex, insight into these associations. As presented in Table ***, open microhabitats with feeding birds in summer expressed significantly higher avian species abundances than several other metrics, as did spring shrub territorial/mating behaviors (though the former still exceeded the latter). This aligns with our previous findings that spring shrubs are important for migrating birds, which are seeking new territories for rest and nests [@Lima2009]. However, the importance of open summer microhabitats for feeding birds conflicts somewhat with our earlier conclusion that open microhabitats in summer are less occupied by birds. Here, we see that summer open microhabitat feeding behaviors dominate summer open inactivity and territorial/mating behaviors, summer cactus feeding behaviors, and spring shrub territorial/mating and cleaning behaviors. This is reality that foraging, specifically, is still necessary in open microsites, particularly as seeds and fruit begin to drop beneath the canopy of the mother plant, but are quickly foraged by seed predators (i.e. granivorous birds) [@Racsko2007; @Janzen1970]. This is to say that in terms of food acquisition, birds cannot operate as we would expect under the stress gradient hypothesis if it is true that food is not available as frequently with the foundation plants during this particularly harsh time. When considering, however, that migration is a highly intensive period for birds [@Guglielmo2001; @Rattenborg2004] we can see that stress is still influencing the association with foundation plants. In fact, this concept falls neatly within the well-known idea that animals must behaviorally adapt to harsh environments [@Filazzola2017]. However, further investigations should more closely monitor the reproductive output of plants which do and do not secure bird visitations and behaviors at different seasons. 
	When considering only one species, the Black-throated Sparrow, we did not see that variety was still important. But when we consider this species’ flexibility in niche, this is not surprising. As a generalist [@Kozma1997], Black-throated Sparrows have an ability to function with multiple habitats [@Kozma2017]. To avoid increasing pressures on a particular microhabitat at a particular time of year in a particular behavioral fashion by a large population, like the Black-throated Sparrow, multiple microhabitats must be available. Without this, more specialist species which overlap in niche with the Black-throated Sparrow may be outcompeted to some degree [@Julliard2006]. It is thanks to this variety of microhabitats that generalists are indeed able to partition microhabitat use, as has been thoroughly documented in small mammals [@Price1978; @Jorgensen2004]. 
 	We suggest that these findings are significantly helpful to environmental managers and conservationists who must make decisions about how restoration—which largely takes the form of plant choice, genetic management, and distribution [@Aavik2018]—should take place. Commonly, managers may resort to planting one, functionally-similar-to-a-rarer-plant plant species to provide microhabitat at lower costs and effort [@Holl2000]. However, birds (and likely other vertebrate species) require a range of microhabitats in environments with varying degrees of stress and varying types of pressures, and for successful, community-wide restoration efforts, this range of needs must be fully considered. 
Conclusion
	Considering both ends of plant-animal interactions forms a greater understanding of the needs of both interactors. Conservationists and ecologists should be sure include all pressures a target species must face. This study specifically addresses the need for comprehensive knowledge on 1) abiotic, ecosystem-wide forces like temperature & water, 2) situational, temporal pressures like migration & territory establishment, 3) species-specific functionalities like trophic guild, and 4) microhabitat provisions like cover, fruit, & floral resources; but many more pressures exist and should be investigated as unique, though interconnected influencers on associations. Our study focuses on desert microhabitats and birds as this ecosystem provides stark differences and consistently mapped pressures, but this heuristic can be applied to any ecosystem. With this knowledge, we can make more holistic management choices that preserve ecosystem functionality.  

References:
